### PR TITLE
Feat home page

### PR DESCRIPTION
**Pull request by hinanshisuthar**
Added Home Page

Preview:
[Native Paws | Home - 11 February 2022 - Watch Video](https://www.loom.com/share/f45a5385f9924a2cba791a7ec75225f6)

### CODE REVIEW

**Review by MaruthiPothuganti — APPROVED** [review]
Made use of the utility classes pretty good. Eye-soothing UI and Code looks clean.

**Review by omgaikwad — APPROVED** [review]
Code is good, UI looks soo cool! Good work!

**Review by Hamdrive — COMMENTED** [review]
No changes to suggest, 

But really stoked by the website created! Landing page looks like an actual professional big brand site! Superb work done !

**Comment by hinanshisuthar** [comment]
> No changes to suggest,
> 
> But really stoked by the website created! Landing page looks like an actual professional big brand site! Superb work done !

**Review by ZuberDunge — APPROVED** [review]
UI is very good, and code is clean too. good work Hinanshi.

**Pull request merged**
